# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            nsftwr ☁️
tagline:          'Cloud Engineer'
description:      'Rudolfs Naumenko'
url:              http://nsftwr.com
baseurl:          /

paginate:         5

