name: Build & Deploy nsftwr.com
on: 
  push:
    branches:
      - gh-pages
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Main Site
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./main
          destination: ./output/
      - name: Build Blog Site
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./blog
          destination: ./output/blog
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./output
  Deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
